// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA5tFEDigc5eFBLD4OUxNWZkyDyZ2pckk8',
    appId: '1:285403881637:web:9cf61860be18a95d72ed4c',
    messagingSenderId: '285403881637',
    projectId: 'quintech-fa669',
    authDomain: 'quintech-fa669.firebaseapp.com',
    storageBucket: 'quintech-fa669.firebasestorage.app',
    measurementId: 'G-W9TDY6FY76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZURpjJGucnePJP6IB_-KOGj4TeTKELas',
    appId: '1:285403881637:android:c0619e14b783a6e072ed4c',
    messagingSenderId: '285403881637',
    projectId: 'quintech-fa669',
    storageBucket: 'quintech-fa669.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4ePouBYDWqP81NxxEjzO6LHhjnSP2p0g',
    appId: '1:285403881637:ios:c9210a5892d77bf372ed4c',
    messagingSenderId: '285403881637',
    projectId: 'quintech-fa669',
    storageBucket: 'quintech-fa669.firebasestorage.app',
    iosBundleId: 'com.kyw.quintech',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4ePouBYDWqP81NxxEjzO6LHhjnSP2p0g',
    appId: '1:285403881637:ios:45cbd748591c874772ed4c',
    messagingSenderId: '285403881637',
    projectId: 'quintech-fa669',
    storageBucket: 'quintech-fa669.firebasestorage.app',
    iosBundleId: 'com.example.quintech',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA5tFEDigc5eFBLD4OUxNWZkyDyZ2pckk8',
    appId: '1:285403881637:web:c723837d04bca7b072ed4c',
    messagingSenderId: '285403881637',
    projectId: 'quintech-fa669',
    authDomain: 'quintech-fa669.firebaseapp.com',
    storageBucket: 'quintech-fa669.firebasestorage.app',
    measurementId: 'G-80JQX1K6ET',
  );
}
